#!/usr/bin/env ruby
require 'rubygems'
require_relative 'lib/lintron'

begin
  cli = Lintron::CLI.new
  cli.go
rescue JSON::ParserError => e
  puts 'An error occurred while parsing response from Lintron'.colorize(:red)
  puts 'Raw response body: '
  puts response.body
end
