#!/usr/bin/env ruby
require 'rubygems'
require_relative 'lib/lintron'

begin
  cli = Lintron::CLI.new
  violations = Lintron::API.new.violations(cli.pr)

  puts Lintron::TerminalReporter.new.format_violations(violations)
rescue JSON::ParserError => e
  puts "An error occurred while parsing response from Lintron".colorize(:red)
  puts "Raw response body: "
  puts response.body
end
