// Generated by CoffeeScript 1.7.1
(function() {
  var ERROR, IGNORE, WARN;

  ERROR = 'error';

  WARN = 'warn';

  IGNORE = 'ignore';

  module.exports = {
    coffeescript_error: {
      level: ERROR,
      message: ''
    }
  };

}).call(this);
