// Generated by CoffeeScript 1.7.1
(function() {
  var NoInterpolationInSingleQuotes;

  module.exports = NoInterpolationInSingleQuotes = (function() {
    function NoInterpolationInSingleQuotes() {}

    NoInterpolationInSingleQuotes.prototype.rule = {
      name: 'no_interpolation_in_single_quotes',
      level: 'ignore',
      message: 'Interpolation in single quoted strings is forbidden',
      description: 'This rule prohibits string interpolation in a single quoted string.\n<pre>\n<code># String interpolation in single quotes is not allowed:\nfoo = \'#{bar}\'\n\n# Double quotes is OK of course\nfoo = "#{bar}"\n</code>\n</pre>\nString interpolation in single quoted strings is permitted by\ndefault.'
    };

    NoInterpolationInSingleQuotes.prototype.tokens = ['STRING'];

    NoInterpolationInSingleQuotes.prototype.lintToken = function(token, tokenApi) {
      var hasInterpolation, tokenValue;
      tokenValue = token[1];
      hasInterpolation = tokenValue.match(/^\'.*#\{[^}]+\}.*\'$/);
      return hasInterpolation;
    };

    return NoInterpolationInSingleQuotes;

  })();

}).call(this);
