// Generated by CoffeeScript 1.7.1
(function() {
  var RuleProcessor;

  module.exports = RuleProcessor = (function() {
    function RuleProcessor() {}

    RuleProcessor.prototype.rule = {
      name: 'spacing_after_comma',
      description: 'This rule requires a space after commas.',
      level: 'ignore',
      message: 'Spaces are required after commas'
    };

    RuleProcessor.prototype.tokens = [','];

    RuleProcessor.prototype.lintToken = function(token, tokenApi) {
      if (!(token.spaced || token.newLine)) {
        return {
          context: token[1]
        };
      }
    };

    return RuleProcessor;

  })();

}).call(this);
